Checkin

diff --git a/dotfiles/zsh-initExtra-functions b/dotfiles/zsh-initExtra-functions
--- a/dotfiles/zsh-initExtra-functions
+++ b/dotfiles/zsh-initExtra-functions
@@ -75,8 +75,188 @@ function uz() {
     unzip $archive -d $extractDir
 }
 
-if [ -n "$\{commands[fzf-share]\}" ]; then
-    source "$(fzf-share)/key-bindings.zsh"
-    source "$(fzf-share)/completion.zsh"
-fi
+# Change AWS instance type by hostname
+function modify-aws-instance-type() {
+    local hostname=$1
+    if [ -z $hostname ]; then
+        echo "ERR: hostname not provided, usage:"
+        echo "  modify-aws-instance-type HOSTNAME INSTANCE_TYPE"
+        return 1
+    fi
+    local instance_type=$2
+    if [ -z $instance_type ]; then
+        echo "ERR: instance_type not provided, usage:"
+        echo "  modify-aws-instance-type HOSTNAME INSTANCE_TYPE"
+        return 1
+    fi
+
+    local describe_instance=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$hostname")
+
+    local instance_id=$(echo "$describe_instance" | jq -r '.Reservations[].Instances[0].InstanceId')
+    if [ -z $instance_id ]; then
+        echo "ERR: InstanceId not found for $hostname"
+        return 1
+    fi
+
+    echo "$hostname -> $instance_id"
+
+    local curr_instance_type=$(echo "$describe_instance" | jq -r '.Reservations[].Instances[0].InstanceType')
+    if [[ "$instance_type" == "$curr_instance_type" ]]; then
+        echo "$hostname instance type is already $instance_type"
+        return 0
+    fi
+    echo "$hostname instance_type: $curr_instance_type"
+
+    local validate_instance_type=$(aws ec2 describe-instance-types --instance-types $instance_type | jq -r '.InstanceTypes[0].InstanceType')
+    if [[ "$validate_instance_type" != "$instance_type" ]]; then
+        echo "ERR: $instance_type is not a valid instance type"
+        return 1
+    fi
+
+    local state=$(echo "$describe_instance" | jq -r '.Reservations[].Instances[0].State.Name')
+    if [[ "$state" != "stopped" ]]; then
+        echo "stopping $hostname"
+        local state=$(aws ec2 stop-instances --instance-ids $instance_id | jq -r '.StoppingInstances[0].CurrentState.Name')
+        while [[ "$state" != "stopped" ]]; do
+            echo "waiting for $hostname / $instance_id state = 'stopped', currently $state"
+            sleep 5
+            local state=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$hostname" | jq -r '.Reservations[].Instances[0].State.Name')
+        done
+    fi
+
+    echo "$hostname stopped. modifying instance type to $instance_type"
+
+    if ! aws ec2 modify-instance-attribute --instance-id $instance_id --instance-type $instance_type; then
+        return 1
+    fi
+
+    echo "starting $hostname"
+
+    local state=$(aws ec2 start-instances --instance-ids $instance_id | jq -r '.StartingInstances[0].CurrentState.Name')
+    echo "$hostname is in $state state"
+    return 0
+}
+
+
+
+# For the given hostname, output the IPs and the AZs they are in
+function get-az-ips-for-hostname() {
+    local hostname=$1
+    if [ -z $hostname ]; then
+        echo "ERR: hostname not provided, usage:"
+        echo "  get-az-ips-for-hostname HOSTNAME"
+        return 1
+    fi
+
+    local ips=$(dig $hostname | grep -A3 "ANSWER SECTION" | tail -3 | rev | cut -d " " -f1 | rev | paste -s -d "," -)
+
+    # Optional
+    local region=$2
+    if [ ! -z $region ]; then
+        local ipDetails=$(AWS_REGION=$region aws ec2 describe-network-interfaces --filters Name=addresses.private-ip-address,Values=$ips)
+    else
+        local ipDetails=$(aws ec2 describe-network-interfaces --filters Name=addresses.private-ip-address,Values=$ips)
+    fi
+
+    # https://www.starkandwayne.com/blog/bash-for-loop-over-json-array-using-jq/
+    for row in $(echo $ipDetails | jq -r '.NetworkInterfaces[] | @base64'); do
+        _jq() {
+            echo ${row} | base64 --decode | jq -r ${1}
+        }
+        local az=$(_jq '.AvailabilityZone')
+        local ip=$(_jq '.PrivateIpAddress')
+        echo "$az - $ip"
+    done
+}
+
+# For the given ingress, discover the domain name for it and output the IPs and the AZs they are in
+function get-az-ips-for-ingress() {
+    local ingress=$1
+    if [ -z $ingress ]; then
+        echo "ERR: ingress not provided, usage:"
+        echo "  get-az-ips-for-ingress INGRESS_NAME"
+        return 1
+    fi
+
+    # Optional
+    local region=$2
+
+    local hostname=$(kubectl get services $ingress --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+
+    get-az-ips-for-hostname $hostname $region
+}
+
+function restart_bluetooth() {
+    if [[ "$OSTYPE" == "darwin"* ]]; then
+        blueutil --power 0 && blueutil --power 1
+    else
+        echo "restart_bluetooth not implemented for $OSTYPE"
+        return 1
+    fi
+}
+
+# HeadPhones
+function hp() {
+    local id="94-db-56-84-69-49"
+    local action=$1
+
+    if [[ "$OSTYPE" != "darwin"* ]]; then
+        echo "hp not implemented for $OSTYPE"
+        return 1        
+    fi
+
+    if [[ $action == "c" ]]; then
+        blueutil --connect $id
+    elif [[ $action == "d" ]]; then
+        blueutil --disconnect $id
+    else
+        echo "hp - unknown action: $action"
+        return 1
+    fi
+}
+
+# start squeezelite
+
+function squeezeme() {
+
+    if [[ "$OSTYPE" != "darwin"* ]]; then
+        echo "squeezeme not implemented for $OSTYPE"
+        return 1        
+    fi
+
+    local id="94-db-56-84-69-49"
+    local headphones="WH-1000XM3"
+    
+    if ps -ef | grep squeezelite | grep -v grep; then
+        killall squeezelite
+    fi
+
+    local headphones_connected=$(blueutil --is-connected $id)
+
+    if [ $headphones_connected = "0" ]; then
+        hp c
+    fi
+
+    local headphones_id=$(squeezelite -l | grep $headphones | awk '{print $1}')
+
+    squeezelite -n macos -d all=info -o $headphones_id &
+}
+
+
+# Third-party functions
+
+##### fzf #### (https://github.com/junegunn/fzf)
+
+# Use fd (https://github.com/sharkdp/fd) instead of the default find
+# command for listing path candidates.
+# - The first argument to the function ($1) is the base path to start traversal
+# - See the source code (completion.{bash,zsh}) for the details.
+function _fzf_compgen_path() {
+    fd --hidden --follow --exclude ".git" . "$1"
+}
+
+# Use fd to generate the list for directory completion
+function _fzf_compgen_dir() {
+    fd --type d --hidden --follow --exclude ".git" . "$1"
+}
 
